#-Basic info----------------------------------------------------------------------------------------
display_name: cge_resfinder
name: &name cge_resfinder__v2_2_3__d98c13b
version:
  schema: ["v2_1_0"]
  code: v2_2_3
  resource: "d98c13b"
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    This performs read based mapping against the resfinder and pointfinder DBs. The options show the species entries 
    which will be used for pointfinder. This is done against using kma mode. 
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [resistance]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_cge_resfinder
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  resfinder_current_species: {Campylobacter,
                              Campylobacter jejuni,
                              Campylobacter coli,
                              Enterococcus faecalis,
                              Enterococcus faecium,
                              Escherichia coli,
                              Helicobacter pylori,
                              Klebsiella,
                              Mycobacterium tuberculosis,
                              Neisseria gonorrhoeae,
                              Plasmodium falciparum,
                              Salmonella,
                              Salmonella enterica,
                              Staphylococcus aureus}
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  #adapters_fasta: "/bifrost/components/bifrost_min_read_check/resources/adapters.fasta"
  resfinder_db: "/bifrost/components/bifrost_cge_resfinder/resources/resfinder_db"
  pointfinder_db: "/bifrost/components/bifrost_cge_resfinder/resources/pointfinder_db"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      resistance:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      resistance:
        title: "Resistance"
        info: *name
        columns: 
          - {id: "phenotype", name: "phenotype"}
          - {id: "seq_regions", name: "seq_regions"}
          - {id: "amr_classes", name: "amr_classes"}
        data: []
  sample_component:
    summary:
      phenotypes: 
    results:
      cge_resfinder/resfinder_results/std_format.json: {}

#---------------------------------------------------------------------------------------------------
